# Generated by Django 3.2 on 2021-10-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_headingdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='news',
            name='news_view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
