# Generated by Django 3.2.6 on 2022-04-18 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newslocation_division_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='ads_img')),
                ('ads_show_page', models.CharField(choices=[('homepage', 'homepage'), ('detailpage', 'detailpage'), ('categorypage', 'categorypage')], max_length=100)),
            ],
        ),
    ]
